modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Blackout03/Mythical-Biomes/issues"
displayURL="https://github.com/Blackout03/Mythical-Biomes"
license="https://github.com/Blackout03/Mythical-Biomes/blob/main/LICENSE"

[[mods]]
    modId="mythicalbiomes"
    version="${file.jarVersion}"
    displayName="Mythical Biomes"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mythicalbiomes"
    itemIcon = "mythicalbiomes:michrosia_log"
    updateJSONURL=""
    logoFile="icon.png"
    credits=""
    authors="Blackout"
    description='''Thanks to the people who created Abnormal Core.'''

[[dependencies.mythicalbiomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,]"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicalbiomes]]
    modId="forge"
    mandatory=true
    versionRange="[36.1.30,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicalbiomes]]
    modId="abnormals_core"
    mandatory=true
    versionRange = "[3.1.1,)"
    ordering="AFTER"
    side="BOTH"