modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="http://my.issue.tracker/"
displayURL=""
license="MIT License"

[[mods]]
    modId="mythicalbiomes"
    version="${file.jarVersion}"
    displayName="Mythical Biomes"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/mythicalbiomes"
    updateJSONURL=""
    #updateJSONURL="https://raw.githubusercontent.com/Blackout03/Version/master/mythicalbiomes_update.json"
    logoFile="icon.png"
    credits=""
    authors="Blackout, Abnormal Core Developers"
    description='''NULL'''

[[dependencies.mythicalbiomes]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicalbiomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"

[[dependencies.mythicalbiomes]]
    modId="abnormals_core"
    mandatory=true
    versionRange = "[3.0.6,)"
    ordering="AFTER"
    side="BOTH"